### PR TITLE
TYPO3 13 compatibility

### PR DESCRIPTION
**Pull request by thomasrawiel**
Should work, but somehow the extended News model isn't recognized in the `NewsDetailActionEventListener`

see: https://github.com/georgringer/news/issues/2527

### CODE REVIEW

**Comment by thomasrawiel** [comment]
Tested this again with the [Bugfix](https://github.com/georgringer/news/commit/16c9970c207057e65e6fc8a3eacb83556a21c629). 
Looks good to me

**Comment by georgringer** [comment]
can you also update the ext_emconf?

**Comment by thomasrawiel** [comment]
Updated the ext_emconf.php for LTS 13.4 and EXT:news ^12

**Comment by oliverklee** [comment]
This broke compatibility with TYPO3 10LTS due to the changes in `Classes/Utility/FetchUtility.php` in https://github.com/georgringer/news_seo/pull/23/files#diff-e8f59372e612b8c8c637e43e8c7a6348ae1a0af330f2b1aee06f04f09ae78f60.

**Comment by georgringer** [comment]
thanks @oliverklee. released https://github.com/georgringer/news_seo/releases/tag/2.2.2

**Pull request merged**
